spring:
  application:
    name: rag-graph
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 5KH90zCh
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j111
  ai:
    openai:
      chat:
        base-url: https://api.siliconflow.cn
        api-key: sk-wkekvkigaytxuokxdcbrcimuugyawdnxevihgwvxwerdmzqa
        options:
          model: deepseek-ai/DeepSeek-V3
          temperature: 0.5
      embedding:
        base-url: https://api.siliconflow.cn
        api-key: sk-wkekvkigaytxuokxdcbrcimuugyawdnxevihgwvxwerdmzqa
        options:
          model: Qwen/Qwen3-Embedding-0.6B
          dimensions: 1024

rag:
  graph:
    index-name: rag_store_new
    batch-size: 200
    on-startup: false
